CROSS_COMPILE =




# link default target to the rest of object files

all: 
	$(CROSS_COMPILE)gcc writer.c -o writer

writer: writer.c


# rule used to clean objects and targets 

clean:
	rm -f writer.o writer	
